outpath:
    output


seed:
    42

samples:
    22Rv1:
        reads:
            - samples/P000R000.pass.fastq
            - samples/P000R001.pass.fastq
            - samples/P000R002.pass.fastq
        ref: homo_sapiens
        degradation_level: non
        chroms:
            [1, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 21, 22, "X"] # All_chroms
        genes:
            - All_genes
        fusionsim:
            fusion_info:
                ref/fusion/fusion_info.tsv
            random_pair_ratio:
                0.01

exec:
    polyA        : scripts/polyA.py
    degrade    : scripts/degradation.py
    split_file : scripts/split_file.py
    fuser     : scripts/make_fusion_fasta.py
    makert     : scripts/readthrough_genes_to_tsv.py
    randomly_pair : scripts/make_random_pairings.py
    badread    : extern/Badread/badread-runner.py




degradation_level:
    non:
        slope     : 0
        intercept : 0
    low:
        slope     : 5
        intercept : 400
    high:
        slope     : 25
        intercept : 300

polyA_config:
    mean     : 60
    stddev : 20
    mincut : 20
    maxcut : 150

refs:
    homo_sapiens:
        dna.fa    : http://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
        cdna.fa     : http://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
        annot.gtf : http://ftp.ensembl.org/pub/release-97/gtf/homo_sapiens/Homo_sapiens.GRCh38.97.gtf.gz
        dna_contig_filter:
            - dna:scaffold # ignore dna contigs with this tag, useful to keep only fully assembled contigs

badread:
    batches    : 64
    url        : https://github.com/baraaorabi/Badread.git
    tag        : v0.1.5
