outpath:
    /groups/hachgrp/projects/dev-ltr-simulator/analysis/ltr-sim-dev/

seed:
    42

samples:
    P000S000:
        - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R000/P000R000.pass.fastq
        - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R001/P000R001.pass.fastq
        - /groups/hachgrp/projects/ana-22rv1/raw-data/wts/fastq/P000R002/P000R002.pass.fastq
    # P001S000:
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R410/P001R410.pass.fastq
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R411/P001R411.pass.fastq
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R510/P001R510.pass.fastq
    #     - /groups/hachgrp/projects/dev-ont/raw-data/wts/fastq/P001R511/P001R511.pass.fastq

genes:
    # - All_genes
    - ENSG00000169083 # AR
    - ENSG00000187838 # PLSCR3
    - ENSG00000156508 # E2F1

exec:
    ltrsim  : ./ltrsim.py
    polyA   : scripts/polyA.py
    degrade : scripts/degradation.py
    badread : extern/Badread/badread-runner.py
    split_file : scripts/split_file.py

degradation_level:
    non:
        slope     : 0
        intercept : 0
    # nonREP:
    #     slope     : 0
    #     intercept : 0
    # low:
    #     slope     : 5
    #     intercept : 400
    # high:
    #     slope     : 25
    #     intercept : 300

polyA_config:
    mean   : 60
    stddev : 20
    mincut : 20
    maxcut : 150

mapping_settings:
    dna  : splice
    cdna : map-ont

references:
    dna      : /groups/hachgrp/annotations/DNA/92/Homo_sapiens.GRCh38.dna.fa
    dna_fai  : /groups/hachgrp/annotations/DNA/92/Homo_sapiens.GRCh38.dna.fa.fai
    cdna     : /groups/hachgrp/annotations/cDNA/92/Homo_sapiens.GRCh38.92.cdna.all.fa
    cdna_fai : /groups/hachgrp/annotations/cDNA/92/Homo_sapiens.GRCh38.92.cdna.all.fa.fai

annotations:
    gtf : /groups/hachgrp/annotations/GTF/92/Homo_sapiens.GRCh38.92.gtf

badread:
    batches  : 5
    url      : https://github.com/baraaorabi/Badread.git
    tag      : v0.1.5
    coverage : 2x

annotations:
    gtf : /groups/hachgrp/annotations/GTF/92/Homo_sapiens.GRCh38.92.gtf
