outpath:
    output/

seed:
    42

samples:
   ERR3588905:
        reads: samples/ERR3588905.fastq
        SRA: ERR3588905
        ref: drosophila_melanogaster
        degradation_level: non
        chroms:
            - 2L
            - 2R
            - 3L
            - 3R
            - 4
            - X
        genes:
            - All_genes

exec:
    polyA      : scripts/polyA.py
    degrade    : scripts/degradation.py
    split_file : scripts/split_file.py
    badread    : extern/Badread/badread-runner.py

degradation_level:
    non:
        slope     : 0
        intercept : 0
    low:
        slope     : 5
        intercept : 400
    high:
        slope     : 25
        intercept : 300

polyA_config:
    mean   : 60
    stddev : 20
    mincut : 20
    maxcut : 150

refs:
    homo_sapiens:
        cdna.fa: http://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
        annot.gtf:  http://ftp.ensembl.org/pub/release-97/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.22.97.gtf.gz
    drosophila_melanogaster:
        cdna.fa: http://ftp.ensembl.org/pub/release-97/fasta/drosophila_melanogaster/cdna/Drosophila_melanogaster.BDGP6.22.cdna.all.fa.gz
        annot.gtf:  http://ftp.ensembl.org/pub/release-97/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.22.97.gtf.gz

badread:
    batches  : 5
    url      : https://github.com/baraaorabi/Badread.git
    tag      : v0.1.5
